### ISSUE TITLE
New Issues *READ THIS*

### ISSUE THREAD

**Issue by 47MarkIV** [47MarkIV/Absolute-Mek#1]
Please let me know 

- Which version of the pack you are using
- How to recreate the issue
- Your suggestions for a fix

**Comment by 47MarkIV** [comment]
Pictures and crash logs are always helpful too.

**Comment by Fistandantilus1** [comment]
Everytime I try to go to the Nether it crashes my game.
[2019-12-06-1.log.gz](https://github.com/47MarkIV/Absolute-Mek/files/3934223/2019-12-06-1.log.gz)

**Comment by Fistandantilus1** [comment]
Sorry forgot to give the version. It's 1.0.0

**Comment by 47MarkIV** [comment]
I can't read that log, but my guess is that it from a mob that's not rendering right. That's on the list to fix this weekend.

**Comment by 47MarkIV** [comment]
Fixed in 1.1

**Comment by Fistandantilus1** [comment]
Still crashes when I try entering the nether
