### ISSUE TITLE
Ticking Entity Crash

### ISSUE THREAD

**Issue by Andr0oS** [47MarkIV/Absolute-Mek#19]
Pack Version:  1.0.0
Client crashes seemingly at random while playing.
[crash-2019-12-06_16.21.58-client.txt](https://github.com/47MarkIV/Absolute-Mek/files/3934592/crash-2019-12-06_16.21.58-client.txt)
[crash-2019-12-06_16.44.55-client.txt](https://github.com/47MarkIV/Absolute-Mek/files/3934593/crash-2019-12-06_16.44.55-client.txt)
[crash-2019-12-06_16.47.57-client.txt](https://github.com/47MarkIV/Absolute-Mek/files/3934594/crash-2019-12-06_16.47.57-client.txt)
[crash-2019-12-06_17.32.23-client.txt](https://github.com/47MarkIV/Absolute-Mek/files/3934595/crash-2019-12-06_17.32.23-client.txt)
[crash-2019-12-06_13.15.58-client.txt](https://github.com/47MarkIV/Absolute-Mek/files/3934599/crash-2019-12-06_13.15.58-client.txt)
[crash-2019-12-06_14.28.57-client.txt](https://github.com/47MarkIV/Absolute-Mek/files/3934600/crash-2019-12-06_14.28.57-client.txt)
[crash-2019-12-06_14.36.22-client.txt](https://github.com/47MarkIV/Absolute-Mek/files/3934601/crash-2019-12-06_14.36.22-client.txt)

**Comment by 47MarkIV** [comment]
Fixed in 1.1
