### ISSUE TITLE
Polar Wolfes have no spawnlimit

### ISSUE THREAD

**Issue by Nubsi-DE** [47MarkIV/Absolute-Mek#24]
It seems that the mmm:polar_wolf is spawning infinite in cold taiga domes.
After some hours gameplay I had over 400 polar wolfs in my dome and that is way to much.

- Start singleplayer.
- Find a cold taiga dome and go to a safe spot.
- Count wolfes and go AFK for ~1h.
- Count again.

Mod version 1.0.0
I see no config options maybe "No Mob Spawning on Trees" can fix this.

**Comment by 47MarkIV** [comment]
The mod that polar wolves is not acting right in several area and is planned for replacement in v1.1

**Comment by 47MarkIV** [comment]
MMM has been removed in 1.1
