### ISSUE TITLE
Ideas list

### ISSUE THREAD

**Issue by 47MarkIV** [47MarkIV/Absolute-Mek#26]
Pull bedpatch for 1 update and see if that reduces error with morpheus

**Comment by 47MarkIV** [comment]
Change the dank null reward

**Comment by 47MarkIV** [comment]
Make Obsidian a DML drop

**Comment by 47MarkIV** [comment]
Ink sacs or black dye

**Comment by 47MarkIV** [comment]
DML spider

**Comment by 47MarkIV** [comment]
Add crushable things to the machines, like blaze rods

**Comment by 47MarkIV** [comment]
Make the timer a mandatory quest

**Comment by 47MarkIV** [comment]
drawers should have been a quest

**Comment by 47MarkIV** [comment]
Removed unneeded mods - Camoflauge creepers, etc

**Comment by Andr0oS** [comment]
> Ink sacs or black dye

Wither bones can be crafted into a black dye replacement, maybe make those into DML drops from wither models?

**Comment by 47MarkIV** [comment]
turbine valves nbt

**Comment by 47MarkIV** [comment]
Inscriber has NBT on - check all quests
