### ISSUE TITLE
Where are the ores?

### ISSUE THREAD

**Issue by Enevoado** [47MarkIV/Absolute-Mek#3]
Where am I supposed to find diamond/redstone/lapis ores? I looked everywhere and can't find them. And I can't find caves either, only ravines.

**Comment by 47MarkIV** [comment]
Keep looking, that is the challenge is to find a connecting series of tunnels to get low enough. Try veinmining the stone around you to look for connections.

**Comment by Enevoado** [comment]
I see no tunnels. I even changed to spectate mode and couldn't find a single one. Is there a config that I can change to add the caves?

**Comment by 47MarkIV** [comment]
There's nothing to change, it's already on. Sounds like you have odd generation. You might want a reinstall/fresh world. We tested after your comments and found caves/ tunnels. 

For mining, you can find materials on the side of the ravines and then get a digital miner.

**Comment by Enevoado** [comment]
Creating new worlds weren't  helping, so I deleted the pack and downloaded it again. Now the caves are generating :). Thanks and sorry for bothering you.
