### ISSUE TITLE
Bountiful Baubbles

### ISSUE THREAD

**Issue by 47MarkIV** [47MarkIV/Absolute-Mek#30]
Remove/replace the mod

**Comment by SonicSpeedster16** [comment]
Just a note: The Magic Mirror from this mod kinda negates the need for the Mek teleporter. I found the Magic Mirror in one of the Lost Cities chests, and can use it to teleport back to my spawn point instead of making the teleporter for that purpose.

**Comment by 47MarkIV** [comment]
Bountiful Baubble Removed
