### ISSUE TITLE
Revenge Rampage quest changes

### ISSUE THREAD

**Issue by Andr0oS** [47MarkIV/Absolute-Mek#31]
- Change reward for "That's Better" since MMM is no longer in the pack
- Change Farlanders kill quest to be looters instead of the friendly farlanders
- Zombie Pigmen are not counted for the kill quest since they are now from Special Mobs

**Comment by 47MarkIV** [comment]
1. Reward Changed
2. Changed to mystic enderminion
3. Fixed by not allowing special mobs to spawn
