### ISSUE TITLE
Some mobs kills don't count for Deep Learner anymore

### ISSUE THREAD

**Issue by anagram3k** [47MarkIV/Absolute-Mek#35]
Version: Absolute Mek 1.1
Updated from the beta by installing the new pack in multimmc and copying the saves and journeymap folders.

Normal Creepers kills don't count in the deep learner.
Also, confetti creeper mod doesn't work anymore, maybe it is related. When creeper explode they damage the terrain.

The farlanders don't count for the endermen count either. Maybe this is intended? Doesn't remember if they counted in the beta.

**Comment by anagram3k** [comment]
Update: rebel endermans do count in the deep learner
Hey man, thanks for the hard work. This a very fun pack!

**Comment by 47MarkIV** [comment]
Thanks, fit this in the list for 1.2. we didn't realize in the switch to special mobs that they replaced all vanilla mobs. Update planned for the weekend.

**Comment by OlRusty** [comment]
so far it's mostly "normal" mobs that are labelled "special mobs" and name for example it will say

Creeper - Special mobs
a lot of these normal type mobs dont count for the deep mob learner data model. i also went to the nether and ghasts dont work AT ALL - Even killed a giant normal ghast and nothin. 
@anagram3k that farlander quest you have to kill 25 of the trader farlanders you find in those end houses but they are too few too rare. Hoping mark changes that quest to something more common

**Comment by Andr0oS** [comment]
> so far it's mostly "normal" mobs that are labelled "special mobs" and name for example it will say
> 
> Creeper - Special mobs
> a lot of these normal type mobs dont count for the deep mob learner data model. i also went to the nether and ghasts dont work AT ALL - Even killed a giant normal ghast and nothin.
> @anagram3k that farlander quest you have to kill 25 of the trader farlanders you find in those end houses but they are too few too rare. Hoping mark changes that quest to something more common

I referenced the farlanders change in issue #31

**Comment by 47MarkIV** [comment]
Special mobs changed to spawn vanilla mobs instead
