### ISSUE TITLE
RAM Allocation

### ISSUE THREAD

**Issue by EAJ97** [47MarkIV/Absolute-Mek#36]
Hey @47markiv, I just found your channel the other night after looking for random FTB videos. I saw this series and decided to try it out myself and so far so good. Although I am having a bit of an issue with the pack. For instance, I have 32GB of RAM and like to run my packs at a nice minimum of 8GB or more. However, I don't see a place in the FTB Server to change the max allocation. In fact, I made a .bat file that runs the server with the new settings. However, this seems to run the server in two instances. Not separate, but like two consoles of the same server. Is there a more efficient way to do this? I've attached a screenshot of what I mean.
![The cmd is me running the .bat file which opens the .jar](https://user-images.githubusercontent.com/47649243/70681959-e1ddbe80-1c62-11ea-9fb4-b672e5422e4f.PNG)

**Comment by EAJ97** [comment]
I _think_ this is the issue causing my private server's TPS to drop to anywhere between 10-13 constantly. Typing in /forge tps in chat says it's running like that as well as having frame issues so I just want to see if a fix for this will solve any issues. My PC is definitely capable of running the server and client so I'm not too sure what the deal is. I'm eliminating variables as I go and will update with an answer when everything is resolved.

**Comment by 47MarkIV** [comment]
Looks like your bat file is missing some commands and it opens both the console and the GUI by default.  Also within that file is where you set the memory for the server. My apologies, I should have set this for the users. The bat file should contain this line.

java -Xmx4096M -Xms4096M -jar forge-1.12.2-14.23.5.2784-universal.jar nogui

Change the 4096 to whatever memory value you want to run.
