### ISSUE TITLE
Allow for Quartz Stairs to be converted to regular Nether Quartz

### ISSUE THREAD

**Issue by SonicSpeedster16** [47MarkIV/Absolute-Mek#38]
I was very excited to come across a large number of Quartz stairs in one of the lost cities (as I had not been able to procure Nether Quartz yet), only to find that it is impossible to convert the stairs to regular quartz. Perhaps a recipe can be added to allow conversion (using the Mekanism Crusher maybe)?

**Comment by 47MarkIV** [comment]
I'll add that and probably a couple other things that should be able to be crushed down. Thanks!
