### ISSUE TITLE
/dank/null quest should accept any tier

### ISSUE THREAD

**Issue by SonicSpeedster16** [47MarkIV/Absolute-Mek#40]
Having very little redstone and even less lapis, I opted for going straight to the tier 4 (gold) /dank/null in order to conserve those two resources. However, the quest only completes when crafting the tier 1 redstone /dank/null. It should be complete-able with any tier of /dank/null.

**Comment by 47MarkIV** [comment]
Sorry cannot do with quest

**Comment by SonicSpeedster16** [comment]
Understood. Perhaps the non-upgrade tier should be removed so that the player must start with the redstone tier and then upgrade to higher tiers from there? Just an idea.
