### ISSUE TITLE
Suggestion: Add Armory Expansion to pack

### ISSUE THREAD

**Issue by SonicSpeedster16** [47MarkIV/Absolute-Mek#41]
[Armory Expansion](https://www.curseforge.com/minecraft/mc-mods/armory-expansion) is an add-on mod for Construct's Armory that allows for additional metals and alloys to be used as Armor pieces in addition to tool/weapon parts via Tinkers'. It helps to prevent situations of "Why can't I use this material for armor when it works for tool and weapon parts?"

I am familiar with the Construct's Armory mod (having played with it in my own pack), and typically my go to material choice for armor is Osgloglas. I just spent several hours going through the process of making Osgloglas, only to realize that it does not work as armor without the Armory Expansion mod.

**Comment by 47MarkIV** [comment]
Accepted & Added in 1.3

**Comment by SonicSpeedster16** [comment]
Awesome, thanks! :)
