### ISSUE TITLE
Shell Constructor quest

### ISSUE THREAD

**Issue by LugalEnki** [47MarkIV/Absolute-Mek#42]
The synch core for the shell constructor quest will not come off the crafting table.

**Comment by Andr0oS** [comment]
Can confirm that it won't work in either AE2 (crafting terminal or by pattern), or a vanilla table

**Comment by 47MarkIV** [comment]
works fine on single player in both tables and AE2, hopefully a recipe mismatch on the server which *should* be solved with an update

**Comment by 47MarkIV** [comment]
pulled the mod and deleted the quest in 1.4
