### ISSUE TITLE
Crash upon exiting my server

### ISSUE THREAD

**Issue by AnimalLover567** [47MarkIV/Absolute-Mek#46]
Whenever i exit the server i have set up for this pack it crashes with an Updating screen events crash [here](https://pastebin.com/M9VjJrYP) is the generated crash report. If you can figure it out cool if not that's cool too.

**Comment by 47MarkIV** [comment]
Honsetly, I am not sure why mek tools would crash the pack on exit. I have not tested the pack on MultiMC, curious to see if the same thing happens to you from Twitch.

**Comment by AnimalLover567** [comment]
I just confirmed that it also happens via twitch launcher as well
