### ISSUE TITLE
Glassentials Mod - more like suggestion + enhancement

### ISSUE THREAD

**Issue by OlRusty** [47MarkIV/Absolute-Mek#49]
add tinkers clear glass to the following recipe although not necessary but also convenient so if it doesnt get added it's no big deal. i love the glass though and sand is EVERYWHERE as well. just whether or not you feel like doing that

-glowing glass
-dark glass
-redstone glass
-ethereal glass

**Comment by 47MarkIV** [comment]
Sorry. All the recipes would have to be redone in the mod to make it work,
