### ISSUE TITLE
Typos in quest tasks

### ISSUE THREAD

**Issue by TwistedGate** [47MarkIV/Absolute-Mek#52]
# Work in Progress
Adding more as i (or others) find more.
#### Hydrogen
![Hydrogen](https://user-images.githubusercontent.com/31029668/71520906-cf988d00-28be-11ea-87d3-44a4173a64e4.png)

#### Disassembler
![Disassembler](https://user-images.githubusercontent.com/31029668/71520907-cf988d00-28be-11ea-8fa3-7520ac06affc.png)

#### Ingredients
![Ingredients](https://user-images.githubusercontent.com/31029668/71520908-cf988d00-28be-11ea-9bd7-dc02bfce5384.png)

**Comment by 47MarkIV** [comment]
Fixed in 1.4
