### ISSUE TITLE
Ender Ore can't be processed in Mek machines

### ISSUE THREAD

**Issue by SonicSpeedster16** [47MarkIV/Absolute-Mek#54]
The Ender Ore collected by the Digital Miner (with silk touch) can only be processed by either placing down and breaking with a pickaxe or using the AE2 Grinder. None of the Mekanism machines accept it.

**Comment by ktole1999** [comment]
can it be melted in the smeltery or used in tinker ore crusher?

**Comment by SonicSpeedster16** [comment]
It does not melt in the smeltery but it can be crushed in the Tinker Ore Crusher according to JEI (I have not built the ore crusher).

**Comment by 47MarkIV** [comment]
Added a furnace recipe for ender ore
