### ISSUE TITLE
sea lanterns not craftable

### ISSUE THREAD

**Issue by OlRusty** [47MarkIV/Absolute-Mek#56]
It has been discovered by someone that sea lanterns are not craftable since you need the crystals and there is no way of getting them.
possible suggestions to get around this would be
--add crushing recipe for prismarine crystals where 1 shard = 4 crystal
--add normal crafting tweak where 4 shards = 8 crystals in a 2x2 type grid
--or just make it normal shapeless crafting 1 shard = 2 crystals.
discovered by twistedgate

**Comment by 47MarkIV** [comment]
Sea lanterns removed
