### ISSUE TITLE
Hammah quest + Eye quest - InTimePresence

### ISSUE THREAD

**Issue by OlRusty** [47MarkIV/Absolute-Mek#58]
the quest for the eye should be AFTER the hammer since you need the hammer to get diamond shards to complete the eye quest. 

2 recommendations to fix this issue as it is not documented in the quest line you need hammer first
is to swap the quests
or move the eye quest over after the hammer.

EDIT: discovered by charzinta

**Comment by 47MarkIV** [comment]
Moved quests around in 1.5
