### ISSUE TITLE
Suggestion: Replace Stone Torch quest rewards with Vanilla Torches

### ISSUE THREAD

**Issue by SonicSpeedster16** [47MarkIV/Absolute-Mek#60]
I find it a bit annoying to get Tinker's Stone Torches as quest rewards since they don't work with the Torch Bandolier. It'd be nice to receive only Vanilla Torches as quest rewards so I can actually use them in the Bandolier. The two quests I recommend changing the rewards on are "Let there be (more) light" and "Mega Torch".

**Comment by 47MarkIV** [comment]
Stone torches deleted from reward
