### ISSUE TITLE
Isolinear Chips Quest

### ISSUE THREAD

**Issue by SonicSpeedster16** [47MarkIV/Absolute-Mek#61]
I just crafted the Molecular Inscriber, however the "Isolinear Chips" quest is not recognizing it and will not complete.

**Comment by SonicSpeedster16** [comment]
After looking at this again, I think the reason that the quest is not working is because I already turned in the RoboCop and Terminator quests which then reset since they are repeatable.

Maybe the Isolinear Chips quest shouldn't be dependent on the RoboCop and Terminator quests?

**Comment by SonicSpeedster16** [comment]
I just did a test and re-completing the "Terminator 2" quest but NOT collecting the rewards (and thereby resetting the quest) did allow me to pick up my Molecular Inscriber and complete the "Isolinear Chips" quest.

So removing the dependency on the "RoboCop" and "Terminator 2" quests should fix the problem, especially since the main Matter Overdrive questline (including the Matter Replicator setup) does not require you to be an Android.

**Comment by 47MarkIV** [comment]
Removed the ability to repeat the quests, fixed in 1.5
