### ISSUE TITLE
Endumium Ore can't be processed

### ISSUE THREAD

**Issue by SonicSpeedster16** [47MarkIV/Absolute-Mek#62]
When collecting Endumiun Ore using a silk touch pickaxe, it is impossible to process it in any machines to get Endumium Crystals.

**Comment by 47MarkIV** [comment]
Tested, silk touched ore still works in the mod's steam hammer as intended.

**Comment by SonicSpeedster16** [comment]
The Endumium Ore is from The Farlanders mod (not In Time Presence) and doesn't work in the steam hammer in my testing. Though with that said Endumium Crystals don't really have a use beyond trading with the Traveling Farlanders so it's not a huge deal anyway.
