### ISSUE TITLE
Blaze Rods can't be crushed down into Blaze Powder

### ISSUE THREAD

**Issue by SonicSpeedster16** [47MarkIV/Absolute-Mek#64]
In Issue #26 you mentioned adding a Crusher recipe for Blaze Rods, however in version 1.4 of the pack Blaze Rods cannot be crushed down to Blaze Powder using the Mekanism Crusher.

**Comment by 47MarkIV** [comment]
Added recipe

**Comment by SonicSpeedster16** [comment]
Thanks!
