### ISSUE TITLE
Suggestion: Add In Time Presence Dimensional Ore to Mekanism Crusher

### ISSUE THREAD

**Issue by h0ppsen** [47MarkIV/Absolute-Mek#66]
It can easily be achieved by adding following line to scripts/Mekanism.zs:

`mods.mekanism.crusher.addRecipe(<intimepresence:dimensionalore>, <intimepresence:dimshards> * 2);`

The Crusher crushes one Dimensional Ore to two Dimensional Shards.

**Comment by 47MarkIV** [comment]
Thanks, it would make the balance with the quest uneven.
